---
title: "Week 10"
subtitle: "Managing the use of scientific products"
editor: visual
---

## The Challenge

Most scientific research depends on people working together: from trainees working with a PI in a single lab, to massive consortia of researchers around the globe. Collaborations raise key challenges: who gets credit for the work? Who can re-use the data and code generated by the work? Traditionally, these decisions were made by the PIs. Even the trainees (research assistants, grad students and post-docs) who actually wrote the code and collected the data could only reuse data and code for their own future independent purposes with permission from the PI, and the PI could offer the data and code to new lab members to continue the project, at the PI's discretion. Both larger-scale collaborations, and mandates to make data and code openly accessible, reduce PIs' ability to control (re)use, potentially dramatically increasing the value of scientific products, but also potentially dramatically increasing the risks that these products would be (re)-used in ways that the original PI finds scientifically invalid, ethically troubling, and/or unstrategic for the trainees the PI most wants to protect. In this way, openness might undermine the ability of PIs to protect what they value: both ethics and people. Can tools help?

 

Gewin, V. (2021). ['We need to talk': ways to prevent collaborations breaking down](https://www.nature.com/articles/d41586-021-01573-z). Nature, 594(7863), 462-463.

Gadlin H & Jesssar K. NIH Office of Research Integrity. [Preempting Discord: Prenuptial Agreements for ScientistsLinks to an external site.](https://ori.hhs.gov/preempting-discord-prenuptial-agreements-scientists)

A wild case study of a dispute over data ownership that had to be adjudicated by the journal editors: Fox, P. T., Bullmore, E., Bandettini, P. A., & Lancaster, J. L. (2009). [Protecting peer review: Correspondence chronology and ethical analysis regarding Logothetis vs. Shmuel and Leopold.](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2715868/) *Human brain mapping*, *30*(2), 347-354.

Halchenko, Y. O., & Hanke, M. (2015). [Four aspects to make science open \"by design\" and not as an after-thought.](https://academic.oup.com/gigascience/article/4/1/s13742-015-0072-7/2707572)*GigaScience*, *4*(1), s13742-015.

A podcast episode about collaboration(start at \~9 minutes): [https://open.spotify.com/episode/21zhLxwM946cIh4H4lxW87?si=r2P1xkuKSeqm74IDxPgoQQ&nd=1Links to an external site.](https://open.spotify.com/episode/21zhLxwM946cIh4H4lxW87?si=r2P1xkuKSeqm74IDxPgoQQ&nd=1)

Russ Poldrack's lab guide, new [section on Intellectual Property](https://poldracklab.github.io/research/intellectual_property.html)

## The Tool

## Collaboration agreements and licenses 

### Practical Assignment:

1\. Read the MIT VPR's guidelines on [Authorship, Data Ownership, and Training](https://research.mit.edu/integrity-and-compliance/research-misconduct/best-practices-preventing-research-misconduct) and the policies on [Copyright](https://libraries.mit.edu/distinctive-collections/thesis-specs/#copyright) for PhD theses (you may have to scroll down to find it). VPR is responsible for handling any formal disputes about these issues. Is there any information here you didn't know? That you think more people should know? What do you think of these policies?

2\. Check your lab's documentation (lab manual, mentorship agreements). Is there an explicit discussion of how data, tools, scripts etc. can be used? Does it specifically address what should happen after researchers are no longer affiliated with the lab? You can compare to the "useful resources" we have linked below, for reference. Share what you find. 

3\. Draft text for (i) your own future lab's guide or manual, (ii) your current lab's manual or guide, or (iii)  your own 'departing the lab' agreement with your current PI. Try to specify which kinds of scientific products are created in the collaboration, who has the rights to re-use them (first author? all authors? creator? PI?), who has to give approval for that use (first author? all authors? PI?), and whether there are any time limits on those obligations. Will you share materials you create with specific [licenses](https://creativecommons.org/about/cclicenses/)? Which license will you use and why?

 

 

### Useful resources and links:

Collaborations: defining roles and rights

ManyBabies projects Collaborations - [Definitions, responsibilities, expectations](https://canvas.mit.edu/courses/16735/files/2628372?wrap=1 "ManyBabies projects - Definitions, responsibilities, expectations.pdf")[ Download Definitions, responsibilities, expectations](https://canvas.mit.edu/courses/16735/files/2628372/download?download_frd=1)\-- Version 2.0

ManyBabies [Policies on Derived Projects and PresentationsLinks to an external site.](https://manybabies.github.io/derived_presentations/)

National Cancer Institute's [Field Guide to Team ScienceLinks to an external site.](https://www.cancer.gov/about-nci/organization/crs/research-initiatives/team-science-field-guide/collaboration-team-science-guide.pdf)

Susan Perlman's "Departing Lab Member" [form](https://canvas.mit.edu/courses/16735/files/2628375?wrap=1 "Departing Lab Member Publication Agreement.docx")[Download form](https://canvas.mit.edu/courses/16735/files/2628375/download?download_frd=1)

UK data service: [Data management roles and responsibilities](https://ukdataservice.ac.uk/learning-hub/research-data-management/plan-to-share/roles-and-responsibilities/). 

Belmont Forum [Step-By-Step User Guide for Building a Successful Data Management PlanLinks to an external site.](https://bfe-inf.github.io/toolkit/ddomp.html)

 

Aly, M. (2018). [The key to a happy lab life is in the manual.](https://www.nature.com/articles/d41586-018-06167-w)*Nature*, *561*(7721), 7-8.

Larivière, V., Pontille, D., & Sugimoto, C. R. (2021). [Investigating the division of scientific labor using the Contributor Roles Taxonomy (CRediT)](https://direct.mit.edu/qss/article/2/1/111/97558/Investigating-the-division-of-scientific-labor). Quantitative Science Studies, 2(1), 111-128.

Forscher, P. S., Wagenmakers, E., Coles, N. A., Silan, M. A., Dutra, N. B., Basnight-Brown, D., & IJzerman, H. (2020, May 20). [The Benefits, Barriers, and Risks of Big Team Science](https://psyarxiv.com/2mdxh). PsyArXiv.

Making the Right Moves: A Practical Guide to Scientifıc Management for Postdocs and New Faculty, by Burroughs Wellcome Fund Howard Hughes Medical Institute (2006); [Chapter 12: SETTING UP COLLABORATIONSLinks to an external site.](https://www.hhmi.org/sites/default/files/Educational%20Materials/Lab%20Management/Making%20the%20Right%20Moves/moves2_ch12.pdf)

 

Primack et al (2019) [Co-authors gone bad](https://www.elsevier.com/connect/co-authors-gone-bad-how-to-avoid-publishing-conflicts) -- how to avoid publishing conflicts

 

Licensing

[Guide to choosing a creative commons licenseLinks to an external site.](https://creativecommons.org/choose/%20)

Open Knowledge Foundation: [Guide to Open Data LicensingLinks to an external site.](https://opendefinition.org/guide/data/)

Belmont forum: [Data Management Best Practices & Standards: LicensingLinks to an external site.](https://bfe-inf.github.io/toolkit/bp&s-licensing.html)

OSF guide to [choosing a license for pre-registrationLinks to an external site.](https://help.osf.io/hc/en-us/articles/360019739014-Licensing)

[Ethical licensesLinks to an external site.](https://ethicalsource.dev/licenses/)

Coalition S [Rights Retention strategy](https://www.coalition-s.org/rights-retention-strategy/): all research articles which arise from funding from a cOAlition S Organisation must be licensed CC BY. And [a long blog post](https://scholarlykitchen.sspnet.org/2021/02/17/rights-retention-strategy/) that aims to explain RRS. 

## The Critical Evaluation

What are the challenges involved in managing who can re-use the products of scientific research, and when, and for what? Do you have any personal experience, or stories you have heard, about conflicts arising from different expectations or desires, with regards to (re)use of data or code or tasks? Particularly after a trainee has left an original lab? Could better lab guides and/or explicit agreements help solve this problem?

\(1\) What did you learn about MIT's policies and procedures? (2) What information did you find for your current lab? (3) Share the text you wrote for a lab guide or departing the lab agreement. 

To what degree can these tools address the challenge?
