---
title: "Week 7"
subtitle: "Results are only accessible to very rich institutions."
editor: visual
---

## The Challenge

Scientific progress is theoretically a gradual process that involves many researchers building on one another's work. However, subscriptions to journals are only affordable to the world's wealthiest institutions. To make matters worse, between 75% and 90% of publications are in English. These disparities severely limit who has access to scientific knowledge, and who can engage in the cumulative scientific process, hampering the scientific process and creating an unjust system.

[MIT news release re: ending negotiations with Elsevier](https://news.mit.edu/2020/guided-by-open-access-principles-mit-ends-elsevier-negotiations-0611)

[Chris Bourg's colloquium talk in BCS](https://www.dropbox.com/s/mq417aqg4f3sgsq/Bourg-04-01-2021.mp4?dl=0), April 2021. Chris Bourg is the director of MIT libraries, and led negotiations between MIT and Elsevier. 

[Plan-S: ](https://www.coalition-s.org/why-plan-s/)An Alliance of European funders mandating Open Access. The [wikipedia article](https://en.wikipedia.org/wiki/Plan_S)includes a description of some of the concerns, and why the US refused to join. 

[Who's downloading pirated papers? Everyone](https://www.sciencemag.org/news/2016/04/whos-downloading-pirated-papers-everyone)\| Science. ([PDF](https://canvas.mit.edu/courses/16735/files/2628371?wrap=1 "Bohannon_piratedpapers.pdf")[ Download](https://canvas.mit.edu/courses/16735/files/2628371/download?download_frd=1))

[A short quiz on 'what costs more'](https://virginia.libwizard.com/f/what-costs-more)

In your response paper, describe something you didn't know about publishing that you learned from these sources, and/or a personal experience you had with the costs and benefits of open access publishing. \

## The Tool

## Practical skills assignment

1\. Take the course on [Open Access Publishing](https://www.fosteropenscience.eu/node/2331) at fosteropenscience.edu

2\. Use the Plan-S [Journal Checker Tool](https://journalcheckertool.org/), to check the compliance of the last five papers that were published by your lab. If you aren't in a lab, check the last five scientific papers you were assigned to read for anything except this class. Also for each of these papers, check the journal's website for the APC policy - how much would an author have to pay to make a paper in this journal Open Access, right now?

3\. Find a paper (not by you or your own lab) that was published 'Green Open Access' (self-archived by the author, freely available in the last submitted version, and possibly after an embargo period). Can you get access to both the free and the published paywalled version? Where? How do they differ?

4\. Look up the Google Scholar profile of a senior scientist whose work you know well. Are all of their papers compliant with funder mandates for open access, according to Google Scholar?

In your response paper, describe what you did in fulfilling this practical activity, and any snags you encountered. 

Then give your critical evaluation of Open Access publishing models. How will these changes improve science? What are the remaining challenges?

## Useful links and resources

[Public Library of Science](https://plos.org/about/) publisher

[Open-access publisher PLOS pushes to extend clout beyond biomedicine](https://www.nature.com/articles/d41586-020-01907-3), Nature NEWS, May 2021

[Do you obey public-access mandates? Google Scholar is watching](https://www.nature.com/articles/d41586-021-00873-8)\| Nature NEWS, March 2021

[How Unpaywall is transforming open science](https://www.nature.com/articles/d41586-018-05968-3)\| Nature NEWS, April 2018

[https://unpaywall.org](https://unpaywall.org/)

[My love-hate of Sci-Hub](https://www.science.org/doi/full/10.1126/science.aaf9419)\| Science, Marcia McNutt 

Nature's [Guide to Plan-S](https://www.nature.com/articles/d41586-021-00883-6), April 2021

[Data visualization](http://roarmap.eprints.org/dataviz.html): international open access policies and change over time. 

https://sparcopen.org/people/sparc-africa/

Wikipedia's [list of open access journals](https://en.wikipedia.org/wiki/List_of_open-access_journals). 

[Directory of Open Access Journals](https://www.doaj.org/). 

[One database of funders' requirements for Open Access. (UK)](https://v2.sherpa.ac.uk/juliet/)

[Another database of funders' requirements for Open Access. (US)](http://researchsharing.sparcopen.org/articles)

Ramírez-Castañeda, V. (2020). [Disadvantages in preparing and publishing scientific papers caused by the dominance of the English language in science: The case of Colombian researchers in biological sciences. ](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0238372)PloS one, 15(9), e0238372.

## The Critical Evaluation

Describe the challenge with current publishing models, highlighting something you didn't know about publishing that you learned from these sources, and/or a personal experience you had with the costs and benefits of open access publishing.  Describe what you did in fulfilling this practical activity, and any snags you encountered. Then give your critical evaluation of Open Access publishing models. How will these changes improve science? What are the remaining challenges?
