---
title: "Week 5"
subtitle: "Mistakes go uncaught and uncorrected."
editor: visual
---

## The Challenge

The scientific process is supposed to accumulate better information, and identify and discard mistakes and false beliefs. Incorrect information or interpretations can be introduced into the literature and persist for a while; but ideally, these errors will be found and weeded out. This week, we will talk about how mistaken or false information enters the scientific literature, how it can be prevented, how it can be found, and what happens when it is. In a later week, we will also talk about the professional incentives that promote or prevent people from correcting mistakes. 

Talk by [Simine Vazire at Open Science 2019.](https://www.youtube.com/watch?v=Yf1Ovx-OixE&t=2373s)

Bishop, D. V. (2018). Fallibility in science: Responding to errors in the work of oneself and others. *Advances in Methods and Practices in Psychological Science*, *1*(3), 432-438. 

This [twitter thread](https://twitter.com/ScannLab/status/1434904032678645761?s=20) a grad student wrote about finding a bug in their code, and reckoning with the consequences. Sep 6 2021. 

At least the abstract of: Hosseini, M., Hilhorst, M., de Beaufort, I., & Fanelli, D. (2018). [Doing the right thing: A qualitative investigation of retractions due to unintentional error.](https://link.springer.com/article/10.1007%2Fs11948-017-9894-2) *Science and engineering ethics*, *24*(1), 189-206

In part 1 of your response paper, describe something you learned from these resources you didn't already know, and/or a personal experience you've had that really brought home the challenge of catching and correcting mistakes and errors, in your own science or in your lab or in your field. 

## The Tool

### Practical skills assignment

1\. Use a tool for making dynamic executable document (R Markdown; Jupiter Notebook; Matlab Notebook) to write this week's assignment. In your executable document, use your own data (or data from another paper) to make at least one reproducible figure. 

2\. [Zotero has partnered with Retraction Watch](https://www.zotero.org/blog/retracted-item-notifications/) to automatically flag retracted papers in a user's repository. Download [Zotero](https://www.zotero.org/) if you do not already have it, and either import a repository from your current citation manager, or manually import a few papers of your choice if you do not use a citation manager. Look through one of your repositories, and see if any papers are flagged as retracted. If not, add a retracted paper (you can find many on [Retraction Watch's database](http://retractiondatabase.org/RetractionSearch.aspx)) to the repository. Is it correctly flagged as retracted? Do you think this flag is noticeable enough to be a useful tool in preventing use of retracted papers?

 

In part 2 of your response paper, describe what you did in fulfilling this activity. What snags did you hit? What made this process easier or more difficult? Did you find any errors?

### Useful links and resources

Dynamic documents: sharing data and the code to make the figures all at once

-   [[R markdown intro]{.underline}](https://bookdown.org/ejvanholm/WorkingWithData/r-markdown-guide.html)

-   [RMarkDown Tips](https://indrajeetpatil.github.io/RmarkdownTips/) and [RMarkDown Lessons](https://rmarkdown.rstudio.com/lesson-1.html)(particularly the first 9).

-   [DataColada: Eight things I do to make my open research more findable and understandable](https://datacolada.org/69)

-   Example of [computational notebook](https://colab.research.google.com/github/losc-tutorial/Data_Guide/blob/master/Guide_Notebook.ipynb#scrollTo=xPpkYz4n8Aov)accompanying [paper](https://iopscience.iop.org/article/10.1088/1361-6382/ab685e), a guide to LIGO--Virgo detector noise and extraction of transient gravitational-wave signals, to reproduce all figures. 

-   Very elegant [RMarkDown document](https://osf.io/2fzx5/)to accompany Julia Leonard's Associations between cortical thickness and reasoning differ by socioeconomic status in development [paper](https://doi.org/10.1016/j.dcn.2019.100641). By downloading the data dictionary & this document, you can reproduce the whole paper, make all figures, etc. 

-   Here's a beautiful example of using interactive visualizations of data and statistics: <https://seeing-theory.brown.edu/index.html>

-   eLife Executable Research Articles <https://elifesciences.org/for-the-press/eb096af1/elife-launches-executable-research-articles-for-publishing-computationally-reproducible-results>

-   QRESP: [https://qresp.org](https://qresp.org/), The open source software Qresp "Curation and Exploration of Reproducible Scientific Papers" facilitates the organization, annotation and exploration of data presented in scientific papers.

Detecting and responding to mistakes and fraud

-   A proposal to replace peer review with "Red Teams". An author gave 'red teams' a financial incentive to find errors in a submission-ready manuscript.

    -   Why? [Part 1.](http://www.the100.ci/2020/06/29/red-team-part-1/)

    -   What happened? [Part 3](http://%20http//www.the100.ci/2020/07/01/red-team-part-3/)

-   [The Buck stops nowhere](https://jamesheathers.medium.com/the-buck-stops-nowhere-8284a57c88c9). Blog about being the "Data police", James Heathers 2017

-   [Evidence of Fraud in an Influential Field Experiment About Dishonesty](https://datacolada.org/98)- Aug 2021, DataColada.

-   [The fight against fake-paper factories that churn out sham science](https://www.nature.com/articles/d41586-021-00733-5). Nature News Feature,\
    23 March 2021

-   <https://retractionwatch.com/>(I found the FAQ interesting) & [tool](http://retractiondatabase.org/RetractionSearch.aspx)for searching the retraction watch database

-   [DataColada: Reducing Fraud in Science](https://datacolada.org/40)

-   Notes from [Computational Research Integrity Day 2021](https://copy-shake-paste.blogspot.com/2021/03/computational-research-integrity-2021.html)

-   Schneider, J., Woods, N. D., Proescholdt, R., Fu, Y., & Team, T. (2021, July 29). [Recommendations from the Reducing the Inadvertent Spread of Retracted Science: Shaping a Research and Implementation Agenda Project.](https://osf.io/preprints/metaarxiv/ms579/)<https://doi.org/10.31222/osf.io/ms579>

-   Serra-Garcia, M., & Gneezy, U. (2021). [Nonreplicable publications are cited more than replicable ones.](https://pubmed.ncbi.nlm.nih.gov/34020944/)*Science advances*, *7*(21), eabd1705.

-   [A bibliography of papers about retraction.](https://infoqualitylab.org/projects/risrs2020/bibliography/) 

-   Suelzer, E.M., Deal, J., Hanus, K.L. (2020). [Challenges in discovering the retracted status of an article.](https://www.ideals.illinois.edu/bitstream/handle/2142/108367/Thought%20piece-Challenges%20in%20discovering%20the%20retracted%20status%20of%20an%20article.pdf?sequence=2&isAllowed=y)

## The Critical Evaluation

The Challenge: Incorrect information or interpretations can be introduced into the literature and persist for a while; but ideally, these errors will be found and weeded out. This paragraph could describe something specific you learned from the readings you didn't already know, and/or a personal experience you've had that really brought home the challenge of science as self-correcting.

The tool: Describe what you did in fulfilling this activity. What snags did you hit? What made this process easier or more difficult? Did you find any errors?

-   Download RStudio and complete the RMarkDown lessons. Try producing a figure from data you've collected or data from your lab. If you don't have access to such data, find an openly shared RMarkDown document and reproduce a figure from that paper.

-   Download Zotero if you don't already have it, and check for retracted papers. If none are flagged, add a retracted paper from Retraction Watch and see if Zotero correctly flags it as retracted. Is this flag noticeable enough to be a useful tool in preventing use of retracted papers?

Critical evaluation of the tool. What is the promise of this tool in addressing this challenge? What are the biggest obstacles? 

This response paper should be about a page long, single-spaced.
