---
title: "Week 11"
subtitle: "Ideas and scrutiny from some people are undervalued"
editor: visual
---

## The Challenge

Throughout the history of academia, people who hold marginalized identities, including those based on race, ethnicity, gender, LGBTQ status, and disability status, are underrepresented in faculty, post-doctoral, and graduate researcher positions (compared to both the U.S. population and the undergraduate population of colleges and universities).  The problem of underrepresentation goes beyond statistics about employment, many have argued that communities within science, including the open-science community, silence and exclude people with marginalized identities, including BIPOC scholars, women, those with disabilities, those who do not speak English etc.

Matias JN, Lewis Jr N, Hope E (2021) [Universities Say They Want More Diverse Faculties. So Why Is Academia Still So White?](https://fivethirtyeight.com/features/universities-say-they-want-more-diverse-faculties-so-why-is-academia-still-so-white/) FiveThirtyEight

[Narrow hiring practices at US universities revealed](https://www.nature.com/articles/d41586-022-03065-0)  (if interested, accompanying paper: <https://www.nature.com/articles/s41586-022-05222-x>)

Graduate student [enrollment and time to degree](https://tableau.mit.edu/t/IR/views/LifeSciencesCoalition-MITGraduateStudentData/GradStudents?:isGuestRedirectFromVizportal=y&:embed=y) by department at MIT. 

Pownall, M., Talbot, C. V., Henschel, A., Lautarescu, A., Lloyd, K. E., Hartmann, H., \... & Siegal, J. (2021). [Navigating Open Science as Early Career Feminist Researchers.](https://journals.sagepub.com/doi/pdf/10.1177/03616843211029255)Psychology of Women Quarterly.

Problems with parachute science in the Global South, from [Science Friday](http://sciencefriday.com/segments/parachute-science-problem/)

Crew B (2020) [Women and minority researchers have more original ideas, but white men are rewarded faster. ](https://www.natureindex.com/news-blog/women-and-minority-researchers-have-more-original-ideas-but-white-men-are-rewarded-faster#.YXvr-ATODjg.twitter)Nature Index. 

## The Tool

### Practical skills assignment.

1\. Do a diversity audit for the syllabus of this class, This is a machine-readable bibliography of the main texts: [Tools_2022.txt](https://canvas.mit.edu/courses/16735/files/2885854?wrap=1 "Tools_2022.txt")[ Download Tools_2022.txt](https://canvas.mit.edu/courses/16735/files/2885854/download?download_frd=1), and for a bibliography in a paper by you or from your lab.  One option for code and instructions [here](https://github.com/dalejn/cleanBib) (you may need this file as well because it checks it against a manuscript: [main-1.tex](https://canvas.mit.edu/courses/16735/files/2885857?wrap=1 "main-1.tex")) or another version is [here](https://jlsumner.shinyapps.io/syllabustool/)

2\. Suggest one replacement for an assigned reading or resource that would increase the diversity of authors in this class's syllabus in terms of gender, race/ethnicity, geography or institution, e.g. researchers working in the global south or at HBCUs (Historically black colleges and universities).

3\. Find a paper you could cite in your next paper, that is topically relevant and would increase the diversity of authors in your bibliography, by gender, race/ethnicity, geography, or institution. 

4\. Read PANNING pdf, practice at least one of the 'engaging skills' at the end of the pdf, in a meeting, class, or on Twitter etc. [PANNING Excercise.pdf](https://canvas.mit.edu/courses/16735/files/2628379?wrap=1 "PANNING Excercise.pdf"). 

5\. Look into the DEI work that MIT and BCS are doing, by looking at the BCS DEIJ [website](https://bcs.mit.edu/diversity-equity-and-inclusion-bcs-and-building-46), the school of science [website](https://science.mit.edu/diversity-and-inclusion/), the ICEO [website](https://iceo.mit.edu/mit-diversity-equity-and-inclusion-data/), and/or the institutional research [dashboard](https://ir.mit.edu/diversity-dashboard).  Did you find anything surprising? Programs or resources you wish more people knew about? Anything that should be there but isn't?

### Useful links and other sources.

[**https://www.academics4blacklives.com/**](https://www.academics4blacklives.com/)

A different tool for audits, the [Google chrome extension](https://chrome.google.com/webstore/detail/citation-transparency/cepnbdbhabaljgecaddglhhcgajphbcf?hl=en)

[DEIJ offices can't be effective if they aren't empowered.](https://www.insidehighered.com/views/2020/08/20/diversity-equity-and-inclusion-offices-cant-be-effective-if-they-arent-empowered%20)Inside Higher Ed.

[RISE](https://www.rise4mit.com/)(Reject Injustice through Student Empowerment) is an MIT group whose mission is to fight racism, sexism, and other forms of injustice on our campus to guarantee the right to a safe working and educational environment free of harassment, discrimination, and abuse.

Subbaraman, N. (2020). [How# BlackInTheIvory put a spotlight on racism in academia.](https://www.nature.com/articles/d41586-020-01741-7)Nature, 582(7812), 327-328.

Lantsoght, E. O., Tse Crepaldi, Y., Tavares, S. G., Leemans, K., & Paig-Tran, E. W. (2021). [Challenges and Opportunities for Academic Parents During COVID-19.](https://www.frontiersin.org/articles/10.3389/fpsyg.2021.645734/full#:~:text=The%20COVID%2D19%20pandemic%20and%20related%20lockdown(s)%20created,increased%20challenges%20for%20academic%20parents.&text=A%20US%20survey%20conducted%20in,learning%20facility%20in%20September%202020)Frontiers in Psychology, 3353.

## The Critical Evaluation

How have you personally observed or experienced the challenges described in the resources for this week? What did you learn from these resources that you didn't know before? 

What did you learn from your audits of the class syllabus, and your own bibliography? How did you feel about the exercise of looking for new sources to cite? Was the task difficult or uncomfortable? Did PANNing give you any new insights? Did you learn something new about MIT, SoS, and BCS programs?

Will audits and conscious efforts be effective in creating scientific communities that are more open to contributions and scrutiny from all people, regardless of accidents of birth? What are the limits of these tools and what other change do we need?  

**\
**
