---
title: "Week 8"
subtitle: "Scientific papers are obsolete."
editor: visual
---

## The Challenge

The modern scientific paper has not changed in the past two hundred years.  New technologies such as high-speed internet allow for embedding dynamic interfaces, audio, video, and other graphics into our scientific communication. And the increasing complexity of scientific protocols and analyses might be best communicated with all these extra modalities. Yet the way we communicate research findings is based on a system created when most people typed manuscripts on a typewriter and mailed physical copies of their manuscripts to editors and reviewers. This has resulted in science communication that relies on written text that is full of jargon, acronyms, and is constrained by word, figure and space limits. The scientific content in journal articles is accessible only to experts, if them. How can we make science more accessible to a broader public, including non-expert readers from neighboring disciplines, students and the public with varying levels of expertise? What is the role of graphic design, visual communication, and other 'non-traditional' modes of scientific communication in our work?

**Read the following articles:**

Spitzer S (2018) [Five Principles of Science Communication ](https://www.socialsciencespace.com/2018/04/five-principles-of-science-communication/). From SocialScienceSpace blog. 

Khoury, C. K., Kisel, Y., Kantar, M., Barber, E., Ricciardi, V., Klirs, C., \... & Novy, A. (2019). [Science--graphic art partnerships to increase research impact. ](https://www.nature.com/articles/s42003-019-0516-1)*Communications biology*, *2*(1), 1-5.

Hohman F t al (2020)  [Communicating with Interactive Articles ](https://distill.pub/2020/communicating-with-interactive-articles/)[10.23915/distill.00028 ](https://doi.org/10.23915/distill.00028); And **explore some of the examples:** [https://explorablemultiverse.github.io/# ](https://explorablemultiverse.github.io/#) Use the underlined blue text to see how the graphs etc change with different analysis choices. (It works better if you 'switch to distill layout'.)

Chiarella, D., Yarbrough, J., & Jackson, C. A. L. (2020). [Using alt text to make science Twitter more accessible for people with visual impairments. ](https://www.nature.com/articles/s41467-020-19640-w)Nature Communications, 11(1), 1-3.

[A beautiful museum exhibit about neurons ](https://twitter.com/ARBashford/status/1453547341751984132) and the [2019 Winner of Dance your PhD](https://www.youtube.com/watch?v=nUQvJOSCoi4)

## The Tool

## Practical skills assignment

1\. Look at a science graphics website, like [biorender ](https://biorender.com/). Is there an image that would help you communicate your own research in clear and appealing graphics?

2\. Find a non-traditional format for scientific communication (one of: an interactive Notebook, a [cartoon paper ](https://twitter.com/econimate), a [video abstract ](https://libraries.ou.edu/content/make-video-abstract-your-research%C2%A0), '[two minute paper ](https://www.youtube.com/channel/UCbfYPyITQ-7l4upoX8nvctg)', a podcast, an [oral story ](https://www.storycollider.org/), twitter thread, [dance ](https://www.science.org/content/article/watch-winners-year-s-dance-your-phd-contest), OR a blog post), and the associated paper. Give an example of something that is communicated more clearly in the non-traditional format. 

3\. Find a figure or image on your, or your lab's, website or social media feed that doesn't have [Alt Text (image description) ](https://www.nature.com/articles/s41467-020-19640-w). Draft [good Alt Text ](https://help.siteimprove.com/support/solutions/articles/80000863904)(or actually add it!)

4\. For a paper you know well, draft one of: an interactive executable paper, a cartoon paper, a video abstract, 'two minute paper', a podcast, an oral story, twitter thread OR a blog post. This can be a draft; you're not required to make a finished project. Attach your product with your response paper. Explicitly say, who is your [intended audience ](https://www.nature.com/articles/s42003-019-0516-1). 

 

## Useful links and resources

[Seeing Social Science Bites Podcasts In A New Way​​](https://www.socialsciencespace.com/2020/07/seeing-social-science-bites-podcasts-in-a-new-way%E2%80%8B%E2%80%8B/)

[Journal of visualized experiments ](https://www.jove.com/). 

OU Library guide for making a successful video abstract: [https://libraries.ou.edu/content/make-video-abstract-your-research ](https://libraries.ou.edu/content/make-video-abstract-your-research)

[Repository of many video abstracts](https://wesharescience.com/all)

[The leading strand ](https://www.theleadingstrand.org/#intro): mission is to highlight important research by translating it through visual experiences.

Professional Science Communication: [https://www.beyondboundscreative.com/ ](https://www.beyondboundscreative.com/); 

<https://significantcommunication.eu/>

[https://twitter.com/econimate ](https://twitter.com/econimate)- communicates economics papers in single frame cartoons. 

An example of [Scientific communication as sequential art. ](http://worrydream.com/ScientificCommunicationAsSequentialArt/)vs. [Collective dynamics of 'small world' networks ](http://worrydream.com/refs/Watts-CollectiveDynamicsOfSmallWorldNetworks.pdf)original paper

Two minute papers, a youtube channel for AI: [https://www.youtube.com/channel/UCbfYPyITQ-7l4upoX8nvctg ](https://www.youtube.com/channel/UCbfYPyITQ-7l4upoX8nvctg)

[AAAS Communication Toolkit ](https://www.aaas.org/resources/communication-toolkit), a guide to communicating scientific results in different registers and media

[Story Collider ](https://www.storycollider.org/), true personal stories about science. 

[https://scienceblogs.com](https://scienceblogs.com/)

[Dance your PhD](https://www.science.org/content/article/watch-winners-year-s-dance-your-phd-contest)

Super cool communication mechanism: [Nutshell ](https://ncase.me/nutshell-wip/)(h/t Joyce)

A (failed?) attempt to incentivize better visualization and explanations: [Distill ](https://distill.pub/2021/distill-hiatus/)(h/t Peng)

What not to do: [Scientific diagrams that look like shitposts  ](https://twitter.com/scienceshitpost)(h/t Joyce)

Katelyn M. Baumer, Juan J. Lopez, Surabi V. Naidu, Sanjana Rajendran, Miguel A. Iglesias, Kathleen M. Carleton, Cheyanne J. Eisenmann, Lillian R. Carter, Bryan F. Shaw. [Visualizing 3D imagery by mouth using candy-like models. ](https://www.science.org/doi/10.1126/sciadv.abh0691)Science Advances, 2021; 7 (22): eabh0691

Nwagwu, W.E., & Onyancha, B., B[ack to the Beginning --- The Journal is Dead, Long Live Science ](https://www.researchgate.net/profile/Williams-Nwagwu-2/publication/347522390_36_Back_to_the_beginning/links/5fe0b83c45851553a0df026e/36-Back-to-the-beginning.pdf), The Journal of Academic Librarianship (2015), http://dx.doi.org/10.1016/j.acalib.2015.06.005

## The Critical Evaluation
